Update hive-replace

diff --git a/hive-replace b/hive-replace
--- a/hive-replace
+++ b/hive-replace
@@ -1,15 +1,20 @@
 #!/bin/bash
 
+
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
 SCRIPT_PATH=`dirname $0`
 SCRIPT_NAME=`basename $0`
+TMPDIR="/tmp/tmproot"
+md5_url="http://download.hiveos.farm/VERSIONS.txt"
 url=""
 root_dev=""
 farm_hash=""
 farm=""
+thishive=0
+[[ $(uname -sr) == *hive* ]] && thishive=1
 
 #Prevent start from local console
-[[ $(tty) == *tty* || ! -z $DISPLAY ]] && echo "This script don't work in the local console. Exit" && exit 
+[[ ! -z $DISPLAY ]] && echo "Please, switch to text console (e.g. Alt+Ctrl+F2), and run it from there" && exit 1 ##Check run from GUI
 
 #Get root
 if [[ $(id -u) -ne 0 ]]; then
@@ -18,39 +23,37 @@ if [[ $(id -u) -ne 0 ]]; then
 	exec sudo $0
 fi
 
-
-
 function get {
-	rm /tmp/tmproot/*hive* > /dev/null 2>&1
+	cd $TMPDIR
+	rm $TMPDIR/*hive* > /dev/null 2>&1
 	
-	answer=""
 	[[ ! -z $url ]] && echo -e  "${GREEN}\nCurrent URL|path to HiveOS image is ${YELLOW}\"$url\"${GREEN}.\nIf this URL|path is correct press ENTER, or re-type correct URL|path.${NOCOLOR}"
 	echo -en "${GREEN}\nLink|path to zip-file with HiveOS image (HTTP|FTP link or local|NFS path) : ${NOCOLOR}"
 	read answer
 	[[ ! -z $answer ]] && url=$answer
 	
 	#Copy|download hive image to tmmfs
-	echo -e "${GREEN}Get HiveOS image${NOCOLOR}"
+	echo -e "${GREEN}\nGet HiveOS image${NOCOLOR}"
 	if [[ "$url" == *http* ||  "$url" == *ftp* ]]; then
 		echo ""
 		wget -t 5 --show-progress $url
 		[[ $? -ne 0 ]] && echo "${RED}Download Hive OS image failed. Check url${NOCOLOR}" && return 1
 	else
 		[[ ! -f $url ]] && echo "${RED}Hive OS image not found. Check path${NOCOLOR}" && return 1
-		cp -v $url /tmp/tmproot
+		cp -v $url $TMPDIR
 		[[ $? -ne 0 ]] && echo "${RED}Copy Hive OS image failed${NOCOLOR}" && return 1
 	fi
 	
 	#get correct md5summ from hive repo
-	curl -s http://download.hiveos.farm/VERSIONS.txt > /tmp/tmproot/VERSIONS.txt
+	curl -s $md5_url > $TMPDIR/VERSIONS.txt
 	[[ $? -ne 0 ]] && "${RED}Сan't get the required data from Hive OS server. Check you internet connection${NOCOLOR}" && return 1
 	basename=`basename -s .zip "$url"`
 	archname=`basename "$url"`
-	mdsum=$(sed -n "/$archname/p" /tmp/tmproot/VERSIONS.txt | awk '{print$2}')
+	mdsum=$(sed -n "/$archname/p" $TMPDIR/VERSIONS.txt | awk '{print$2}')
 	
 	#check md5
 	echo "${GREEN}Check MD5 summ of image file${NOCOLOR}"
-	mdsum_hive=$(md5sum /tmp/tmproot/$archname | awk '{print$1}')
+	mdsum_hive=$(md5sum $TMPDIR/$archname | awk '{print$1}')
 	[[ $mdsum != $mdsum_hive ]] && echo "${RED}MD5-summ of image file incorrect${NOCOLOR}" && return 1
 	echo "${GREEN}Download|copy HiveOS image success!${NOCOLOR}"
 	return 0
@@ -68,9 +71,6 @@ function prepare {
 	WHITE=`tput setaf 7`
 	NOCOLOR=`tput sgr0`
 
-	
-	
-
 	mem=$(free -m | awk 'NR == 2{print$2}')
 	clear
 	echo "***********************************"
@@ -85,7 +85,8 @@ function prepare {
 	DISK_NAME=`echo ${DISK_PART} | sed 's/\([[:digit:]]\)//'`
 	DISK_SIZE=`cat /proc/partitions | grep -w "${DISK_NAME}" | awk '{ printf("%.f",$3/1024)}'`
 	PART_SIZE=`cat /proc/partitions | grep -w "${DISK_PART}" | awk '{ printf("%.f",$3/1024)}'`
-
+	
+	
 	echo -e "Current OS booted from ${GREEN}$DISK_NAME${NOCOLOR} and whole drive size is ${WHITE}$DISK_SIZE${NOCOLOR} MB"
 	[[ $DISK_SIZE -lt 8192 ]] && echo -e "\n${YELLOW}The minimum disk size for HiveOS is 8 Gb${NOCOLOR}" && exit
 	echo -e "${RED}Warning: After install HiveOS, all your data on ${GREEN}$DISK_NAME${NOCOLOR}${RED} will be lost!${NOCOLOR}"
@@ -101,25 +102,32 @@ function prepare {
 	[[ $? -ne 0 ]] && programs=1
 	dpkg -s wget > /dev/null 2>&1
 	[[ $? -ne 0 ]] && programs=1
+	dpkg -s unzip > /dev/null 2>&1
+	[[ $? -ne 0 ]] && programs=1
 	if [[ $programs -ne 0 ]]; then
 		echo "Install the necessary programs"
 		apt-get update
-		apt-get install -y lsof curl wget
+		apt-get install -y lsof curl wget unzip
 	fi
-
+	
 	#create tmpfs
-	mkdir /tmp/tmproot > /dev/null 2>&1
-	mount none /tmp/tmproot -t tmpfs -o size=3000m
-	cd /tmp/tmproot
-
-	#get farm_hash
-	farm=""
-	while [[ -z $farm ]]; do
-		echo -en "${GREEN}\nType you FARM_HASH from Web-interface : ${NOCOLOR}"
-		read farm
-		[[ -z $farm ]] && echo "${RED}FAMR_HASH can't be empty. Please retype.${NOCOLOR}"
-	done
-
+	mkdir $TMPDIR > /dev/null 2>&1
+	mount none $TMPDIR -t tmpfs -o size=3000m
+	
+	
+	#get farm_hash or old config
+	if [[ $thishive -eq 1 && -f /hive-config/rig.conf ]]; then
+		cp /hive-config/rig.conf $TMPDIR/
+	else
+		farm=""
+		while [[ -z $farm ]]; do
+			echo -en "${GREEN}\nType you FARM_HASH from Web-interface : ${NOCOLOR}"
+			read farm
+			[[ -z $farm ]] && echo "${RED}FAMR_HASH can't be empty. Please retype.${NOCOLOR}"
+		done
+	fi
+	
+	
 	#get hive zip
 	flag_get=1
 	while [[ $flag_get -ne 0 ]]; do
@@ -134,144 +142,130 @@ function prepare {
 		fi
 	done
 	
+	#Disable kernel message to tty
+	echo 0 > /proc/sys/kernel/printk
+	echo 1 > /proc/sys/kernel/sysrq
+	echo 0 > /proc/sysrq-trigger
 
-	#stop services
+	
+	#stop services and remount RO
 	swapoff -a
 	echo -e "${YELLOW}\nStop services${NOCOLOR}"
+	
+	[[ $thishive -eq 1 ]] && miner stop > /dev/null 2>&1 && killall xinit
+	
 	for SOCKET in \
-		`systemctl list-units -t socket | awk '{print $1}' | grep -v -e ssh | grep -v -e network | grep -v -e user-sessions`; \
-		do systemctl stop $SOCKET > /dev/null 2>&1; done
-
+	`systemctl list-units -t socket | awk '{print $1}' | grep -v -e ssh | grep -v -e ssh | grep -v -e network | grep -v -e ifup | grep -v -e user-sessions`; \
+	do systemctl stop $SOCKET > /dev/null 2>&1; done
 	for SERVICE in \
-		`systemctl list-units -t service | awk '{print $1}' | grep -v -e ssh | grep -v -e network | grep -v -e user-sessions`; \
-		do systemctl stop $SERVICE > /dev/null 2>&1; done
+	`systemctl list-units -t service | awk '{print $1}' | grep -v -e ssh | grep -v -e ssh | grep -v -e network | grep -v -e ifup | grep -v -e user-sessions`; \
+	do systemctl stop $SERVICE > /dev/null 2>&1; done
+	
+	pid="1"
+	while [[ ! -z $pid ]]; do
+		pid=$(lsof / | grep -v ' \(mem\|txt\|rtd\|cwd\) ' | grep -v -e $SCRIPT_NAME | sed '2!d' | awk '{print $2}')
+		[[ -z $pid ]] && continue
+		process=$(lsof / | grep -v ' \(mem\|txt\|rtd\|cwd\) ' | grep -v -e $SCRIPT_NAME | sed '2!d' | awk '{print $1}')
+		echo -e "Kill $process"
+		kill $pid
+		sleep 1
+	done
+
+	for MOUNTS in `cat /proc/mounts | grep $DISK_NAME | awk '{print $2}'`; do mount -n -o remount,ro $MOUNTS > /dev/null 2>&1; done
+	
+	
+	##get config partition and mount it to loop
+	arch=$(ls $TMPDIR/*hive*zip)
+	unzip -p $arch | dd of=$TMPDIR/conf.img bs=1M count=50 iflag=fullblock > /dev/null 2>&1
+	begin_conf=$(( $(fdisk -l $TMPDIR/conf.img | grep NTFS | awk '{print $2}') * 512 ))
+	conf_loop=$(losetup -f)
+	losetup -o $begin_conf $conf_loop $TMPDIR/conf.img
+	mkdir $TMPDIR/hive-config
+	mount $conf_loop $TMPDIR/hive-config
+	
+	if [[ -f $TMPDIR/rig.conf ]]; then
+		cp $TMPDIR/rig.conf $TMPDIR/hive-config/rig.conf
+	else
+		echo -e "HIVE_HOST_URL=\"http://api.hiveos.farm\"" > $TMPDIR/hive-config/rig.conf
+		echo -e "FARM_HASH=$farm\n" >> $TMPDIR/hive-config/rig.conf
+	fi
+
+	#write image of configs partition
+	dd if=$conf_loop of=$TMPDIR/new_conf.img > /dev/null 2>&1
 
 
 	#create temp root
 	echo -e "${YELLOW}\nCreate a temporary root fs${NOCOLOR}"
-	mkdir -p /tmp/tmproot/{proc,sys,run,usr,var,oldroot,bin,sbin,lib,tmp,usr/lib,usr/share,usr/lib/x86_64-linux-gnu,lib/lsb}
+	mkdir -p $TMPDIR/{proc,sys,run,dev,usr,var,oldroot,bin,sbin,lib,tmp,usr/lib,usr/share,usr/lib/x86_64-linux-gnu,lib/lsb}
+	cp -aR /{bin,sbin,etc} $TMPDIR > /dev/null 2>&1
+	cp -aR /usr/{bin,sbin} $TMPDIR/usr > /dev/null 2>&1
+	cp -aR /lib/x86_64-linux-gnu $TMPDIR/lib > /dev/null 2>&1
+	cp -aR /lib64 $TMPDIR > /dev/null 2>&1
+	cp -aR /usr/lib/sudo $TMPDIR/usr/lib > /dev/null 2>&1
+	cp -a /usr/lib/x86_64-linux-gnu/libmpfr* $TMPDIR/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
+	cp -a /usr/lib/x86_64-linux-gnu/libsigsegv* $TMPDIR/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
+	cp -a /usr/lib/x86_64-linux-gnu/libgmp* $TMPDIR/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
+	cp -aR /dev $TMPDIR > /dev/null 2>&1
+	cp $0 $TMPDIR > /dev/null 2>&1
+	chmod +x $TMPDIR/$SCRIPT_NAME > /dev/null 2>&1
 
-	cp -aR /var/log /tmp/tmproot/var > /dev/null 2>&1
-	cp -aR /var/run /tmp/tmproot/var > /dev/null 2>&1
-	cp -aR /run /tmp/tmproot/run > /dev/null 2>&1
-	cp -aR /{bin,sbin,etc} /tmp/tmproot > /dev/null 2>&1
-	cp -aR /usr/{bin,sbin} /tmp/tmproot/usr > /dev/null 2>&1
-	cp -aR /lib/x86_64-linux-gnu /tmp/tmproot/lib > /dev/null 2>&1
-	cp -aR /lib/systemd /tmp/tmproot/lib > /dev/null 2>&1
-	cp -aR /lib64 /tmp/tmproot > /dev/null 2>&1
-	cp -aR /usr/lib/sudo /tmp/tmproot/usr/lib > /dev/null 2>&1
-	cp -aR /usr/lib/locale /tmp/tmproot/usr/lib > /dev/null 2>&1
-	cp -aR /usr/lib/x86_64-linux-gnu/gconv /tmp/tmproot/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
-	cp -aR /usr/share/locale-langpack /tmp/tmproot/usr/share > /dev/null 2>&1
-	cp -a /usr/lib/x86_64-linux-gnu/libkrb5* /tmp/tmproot/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
-	cp -a /usr/lib/x86_64-linux-gnu/libk5* /tmp/tmproot/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
-	cp -a /usr/lib/x86_64-linux-gnu/libgssapi* /tmp/tmproot/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
-	cp -a /usr/lib/x86_64-linux-gnu/libcrypto* /tmp/tmproot/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
-	cp -a /usr/lib/x86_64-linux-gnu/liblz* /tmp/tmproot/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
-	cp -a /usr/lib/x86_64-linux-gnu/libmpfr* /tmp/tmproot/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
-	cp -a /usr/lib/x86_64-linux-gnu/libsigsegv* /tmp/tmproot/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
-	cp -a /usr/lib/x86_64-linux-gnu/libgmp* /tmp/tmproot/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
-	cp -a /lib/lsb/init-functions /tmp/tmproot/lib/lsb > /dev/null 2>&1
-	cp -aR /dev /tmp/tmproot/dev > /dev/null 2>&1
-	cp $0 /tmp/tmproot > /dev/null 2>&1
-	chmod +x /tmp/tmproot/$SCRIPT_NAME > /dev/null 2>&1
-
-	#change root fs to temp
-	mount --make-rprivate none /
-	cd /tmp/tmproot
-	pivot_root . oldroot
-	cd /
-
+	mount --bind /proc $TMPDIR/proc
+	mount --bind /sys $TMPDIR/sys
+	mount --bind /dev $TMPDIR/dev
 	
-	#mount new sys fs
-	mount -n --move /oldroot/proc /proc
-	mount -n --move /oldroot/dev /dev
-	mount -n --move /oldroot/sys /sys
-	mount -n --move /oldroot/run /run
-
 	#create conf for second part
-	sync
-	echo "root_dev=$DISK_NAME" > /replace.conf
-	echo "farm_hash=$farm" >> /replace.conf
-	echo "WHO=\"$(who am i)\"" >> /replace.conf
+	echo "wr=1" > $TMPDIR/replace.conf
+	echo "root_dev=$DISK_NAME" >> $TMPDIR/replace.conf
+	echo "conf_loop=$conf_loop" >> $TMPDIR/replace.conf
 	
-	#restart ssh and exit from first part
-	[[ -f /etc/init.d/ssh ]] && /etc/init.d/ssh restart > /dev/null 2>&1
-	echo -e "${GREEN}\nFirst part installation of Hive OS completed.${NOCOLOR}"
-	echo -e "${GREEN}To continue, open a new SSH session to this computer,\nand there run ${YELLOW}\"/$SCRIPT_NAME\"${GREEN} as ${YELLOW}root${NOCOLOR}"
+	#Cehroot to temp root
+	mount --bind /proc $TMPDIR/proc
+	mount --bind /sys $TMPDIR/sys
+	mount --bind /dev $TMPDIR/dev
+	sync
+	cd $TMPDIR
+	exec chroot . /bin/bash /$SCRIPT_NAME
+
 }
 
 function write {
 	cd /
-	
-	#prevention of execution in the same SSH-session
-	now_who="$(who am i)"
-	[[ $remote -eq 1 && $now_who == $WHO ]] && echo "Can't start in the same SSH-session." && return
 
-	telinit u > /dev/null 2>&1
-	systemctl daemon-reload > /dev/null 2>&1
-		
-
-	echo -e "\nKill all processes that keep open files on old root"
-	for PROCESS in `lsof -t /oldroot`; do kill $PROCESS; done
-
-	#Umount old root
-	for MOUNTS in `cat /proc/mounts | grep oldroot | grep -v -e "/oldroot " | awk '{print $2}'`; do umount $MOUNTS > /dev/null 2>&1; done
-	sleep 1
-	umount /oldroot > /dev/null 2>&1
-	
-	sleep 1
-	[[ ! -z $(cat /proc/mounts | grep oldroot) ]] && echo -e "Umount old root fs failed. Exit" && return
-	echo -e "\nUmount old root file system success."
-	
 	arch=$(ls *hive*zip)
-
+	conf_part=$root_dev"1"
+	
 	echo -e "\n\nCreate a HIVE OS File system on $root_dev"
 	echo -e "\nPlease wait. This can take a long time."
 	echo -e "To prevent damage to your disk device,\ndo not turn off your computer until the end of the process.\n"
 
-	unzip -p $arch | dd of=/dev/$root_dev status=progress bs=10M
+	unzip -p $arch | dd of=/dev/$root_dev status=progress bs=20M
 	[[ $? -ne 0 ]] && "Write image failed. Exit" && return
 
-	echo -e "\nCreate a HIVE OS File system on $root_dev successfull!"
-	echo -e "\nCheck new partitions and configure HiveOS"
 
+	#Rewrite config partition
 	partprobe > /dev/null 2>&1
-	part_conf="/dev/$root_dev""1"
-	part_hive="/dev/$root_dev""2"
-	ntfsfix $part_conf
-	fsck.ext4 $part_hive
-	mkdir /hive-config
-	
-	#Mount hive-config and create rig.conf
-	mount -t ntfs-3g -o rw $part_conf /hive-config
-	
-	echo "HIVE_HOST_URL=\"http://api.hiveos.farm\"" > /hive-config/rig.conf
-	echo "FARM_HASH=$farm_hash" >> /hive-config/rig.conf
-	echo "" >> /hive-config/rig.conf
-	
-	
-	echo
+	dd if=/new_conf.img of=/dev/$conf_part > /dev/null 2>&1
+
+	#Reboot
+	sync
+	echo -e "\nCreate a HIVE OS File system on $root_dev successfull!"
+
 	echo -e "\nYour rig is configured and ready to work under Hive OS."
 	echo "After the reboot, it will be automatically registered on the web"
 	echo "as part of the farm whose FARM HASH you entered"
 	echo
-	echo "Happy mining!"
+	echo -e "\nHappy mining!"
 	echo "Reboot"
-	sync
-	umount /hive-config
 	sleep 15
-	
-	#Sysrq Reboot
+
 	echo 1 > /proc/sys/kernel/sysrq
 	echo b > /proc/sysrq-trigger
 }
 
-
-
 function sel {
-	[[ -f /replace.conf ]] && source /replace.conf
-	if [[ ! -z $root_dev && ! -z $farm_hash && ! -z $(cat /proc/mounts | grep oldroot) ]]; then
+	wr=0
+	[[ -f replace.conf ]] && source /replace.conf
+	if [[ $wr -eq 1 ]]; then
 		write
 	else
 		prepare
@@ -280,3 +274,4 @@ function sel {
 
 
 sel
+
